### ISSUE TITLE
1.2.4 Gather initial project requirements

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#16]
Tasks:
- [x] Identify the full set of features and functionalities from the client
- [x] Categories them into functional and non-functional

**Comment by wqyeo** [comment]
Waiting on #15 

> Linked to #8 as well

**Comment by wqyeo** [comment]
Features have been identified, remaining is to log it down in documentation...

broke it down into issues #34 and #33

**Comment by 2202282** [comment]
Summary: 
Identified a comprehensive set of features and functionalities from the client. These have been thoughtfully categorized into two distinct sections: functional elements, which are documented under issue #33, and non-functional aspects, which have been detailed under issue #34.

Duration: 2 days
Start/end: 5/9/23 to 7/9/23
