### ISSUE TITLE
Collect Industry Standards and Regulations

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#17]
In the document, fill up the respective sections:

- Related Background Literature
- Domain Specific Research
- Existing Solutions

> Background research is required for those sections...

**Comment by wqyeo** [comment]
Completed it on the document, check the document for more information...

**TLDR;** Research is done in similar systems _(Workload Management Systems)_ in multiple industries, and exploration on similar productions/applications as well.

Linked to #21 , #8 , #16 

**Duration:** collectively over 2 days
Start/end date: 15/9/23 to 16/9/23
