### ISSUE TITLE
2.3.2 Create Sequence Diagram - Allocate Job to staff

### ISSUE THREAD

**Issue by wqyeo** [Juicy-Lemonberry/INF2001-P5-2#18]
Tasks:
Create UML Sequence Diagram for these following interactions:

- [x] How the manager would allocate workload to workers.
- [x] How the workers would allocate their availability and preferences.
- [x] How would workers reject a job given.

-----

**Optionally**
- [ ] Login process for workers/managers.
- [ ] How would an IT Staff create new accounts for worker/managers.

-----

Goals: To create the sequence diagram for 'Allocate Job to staff' use case
Completion Criteria: The sequence diagram must encompass the flow based on the use case description and class diagram.
Allocated Time: 8 days
Start & End date : 27/9/23 to 6/10/23

**Comment by wqyeo** [comment]
Also, waiting on #15 to finalize diagram idea.

**Comment by wqyeo** [comment]
## Sequence Diagram for how managers would allocate workload to users

![M1_Diagrams-Manager-Workload-Assignment-Sequence-Diagram](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/7fec79ea-a96e-412d-a8cd-d2db09d4dd62)

**Comment by Zhwee** [comment]
Flow of sequence diagram is done, and attributes are based off of the class diagram
