### ISSUE TITLE
1.3.5 Create activity diagrams - Managers

### ISSUE THREAD

**Issue by wqyeo** [Juicy-Lemonberry/INF2001-P5-2#19]
Tasks:
- [x] Create UML Activity Diagram for the Managers of the system.

**Comment by wqyeo** [comment]
![Image](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/9a5e53f2-77cf-4419-88df-e35d31ab8d1c)

Refactored diagram further to include some more possible flow-cases, check the draw.io file in drive for more details.

@kazoohaa should check it again....

**Comment by kazoohaa** [comment]
Summary:
Wen Qin created an activity diagram specifically designed for manager, facilitating a clear visual representation of their roles and processes within the project.

Duration: 3 days
Start/end: 12/9/23 to 14/9/23
