### ISSUE TITLE
1.6.1 M1 Report

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#21]
1. Introduction

- [x] 1.1 Product Scope
- [x] 1.2 Related Background Literature
- [x] 1.3 Intended Audience and Document Overview
- [x] 1.4 References and Acknowledgements

2. Overall Description

- [x] 2.1 Product Overview
- [x] 2.2 Product Functionality
- [x] 2.3 Assumptions and Dependencies

3. Specific Requirement

- [x] 3.1 User Interface Requirements
- [x] 3.2 Functional Requirements
- [x] 3.3 User Case Model
- [x] 3.4 Non-functional Requirements

4. Project Estimation and Plan

- [x] 4.1 Software Estimation
- [x] 4.2 Project Management

**Comment by wqyeo** [comment]
State some UI Attributes for User Interface Requirements, such as:

- [x] Language/Locale
- [x] Default Font Size
- [x] Theme, Color Scheme
- [x] Company Logo

**Comment by 2202282** [comment]
Team Lead added the below aspect for User Interface Requirements
- Theme, Color scheme
- Text Font, Size
- Language, Format
- Platform Design (target platform)
- Accessibility

**Comment by Zhwee** [comment]
Summary: 
Full completion of the report, checked and reviewed with more indepth individual components under other issues

Duration: 9 days
Start/end date: 15/9/23 to 23/9/23
