### ISSUE TITLE
1.3.3 Create activity diagram - Staff Members

### ISSUE THREAD

**Issue by wqyeo** [Juicy-Lemonberry/INF2001-P5-2#22]
Tasks:
- [x] Create UML Activity Diagram for the Staff members of the system.

**Comment by wqyeo** [comment]
![Image](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/2b8e7ddd-7430-4674-8e34-16fe0d07c057)

Made some edits to include more possible flows for the staff members to take, awaiting @kazoohaa for review...

**Comment by kazoohaa** [comment]
Summary:
Created an activity diagram specifically designed for staff members, facilitating a clear visual representation of their roles and processes within the project.

**Comment by ivriahtyx** [comment]
Summary:
I created an activity diagram specifically designed for staff members, facilitating a clear visual representation of their roles and processes within the project.

Duration: 3 days
Start/end: 12/9/23 to 14/9/23
