### ISSUE TITLE
1.3.4 Create activity diagrams - IT Admin

### ISSUE THREAD

**Issue by wqyeo** [Juicy-Lemonberry/INF2001-P5-2#23]
Tasks:
- [x] Create UML Activity Diagram for the IT Admins of the system.

**Comment by wqyeo** [comment]
Changes to be made based on results from #15 , reference #8 if needed....

**Comment by wqyeo** [comment]
![Activity_Diagrams-IT-Admin](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/6d5770f0-8076-46b0-8ac7-21a5e6d78f26)

Updated IT Admin Activity Diagram based on #15 in reference to #8 

awaiting review from @kazoohaa before closing...

**Comment by kazoohaa** [comment]
Summary:
Created an activity diagram specifically designed for IT admins, facilitating a clear visual representation of their roles and processes within the project.

Duration: 3 days
Start/end: 12/9/23 to 14/9/23
