### ISSUE TITLE
1.2.6 Review and refine gathered requirements

### ISSUE THREAD

**Issue by Zhwee** [Juicy-Lemonberry/INF2001-P5-2#25]
Tasks:
- [x] Review the functional and non-functional requirements
- [x] Amend the requirement according to the 2 follow-up email

**Comment by Zhwee** [comment]
Conducted a thorough review of both the functional and non-functional requirements. Based on this assessment, We have made necessary revisions to the response provided in our first follow-up email.

**Comment by wqyeo** [comment]
Linked to #43 , #21 

Both reviews was done f2f as a group, check the document for more information on the gathered requirements...

**Duration:** 2 Day
Start/end date: 18/9/23 to 19/9/23
