### ISSUE TITLE
1.2.5 Conduct follow-up questions with stakeholder via email 

### ISSUE THREAD

**Issue by Zhwee** [Juicy-Lemonberry/INF2001-P5-2#26]
- [x] Organise notes to email client #email1
- [x] Send the email to the client
- [x] Organise notes taken from emailing client

**Comment by wqyeo** [comment]
**Potential Questions to Ask:**

- How are `site` or `area` added into databases? _(Will IT staff have functionalities to add them in? Or will business owners have an account to add them in?)_
- How is an `area` defined? How will `site` be added into an `area`? _(Currently, a `site` is part of an `area` if it's within 1km, but where does the point of 1km start from?)_
- How will user training be conducted to allow new users to adopt the system?

**Comment by Zhwee** [comment]
Possible qns to ask:

1. How many sites are there
2. Do they want a visual image, of the different sites (e.g. click on one site/building image, and it will show all the diff staff and timings of that site)

**Comment by wqyeo** [comment]
Message to client sent 👍 , CCed email respectively...

**Comment by 2202282** [comment]
Summary: 
Organized the notes necessary for composing our initial email to the client. Then, sent the follow-up email to initiate the conversation. Subsequently, the client responded to your email, indicating an ongoing dialogue. Lastly, updated our notes accordingly to the client's answer

Duration: 1 day
Start/end: 7/9/23 to 8/9/23
