### ISSUE TITLE
1.4.2 Write use case descriptions - Staff Members

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#31]
Tasks:
- [x] Identify Use Cases
- [x] Name Use Cases
- [x] Write a Brief Description
- [x] List Preconditions
- [x] List Postconditions
- [x] Detail the Main Flow
- [x] Include Alternate Flows
- [x] Specify Exception Handling

*Reference #8  , or the drawio file in the drive...

**Comment by kazoohaa** [comment]
Summary:
Jun hao following up from #8, wrote use case descriptions for staff members in detail for a more comprehensive understanding of the flow of individual use cases within our use case diagram.

Duration: 3 days
Start/end: 15/9/23 to 19/9/23 (inclusive of weekends)
