### ISSUE TITLE
1.3.1 Develop project schedule

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#32]
Tasks:
- [x] Create Gantt Chart
- [x] Add necessary task under milestone 1, 2, 3
- [x] Set the duration for all the task
- [x] Assign the task to each person

**Comment by wqyeo** [comment]
**Update:**

Updated gantt chart for what we have done so far for milestone 1, review as needed

**Comment by 2202282** [comment]
Summary: 
Updated the Gantt Chart for our project. This includes dividing it into milestones 2 and 3, and then populating it with the necessary tasks, each allocated an appropriate duration. Additionally, you've ensured that every task is assigned to its respective team member, streamlining our project's organization and workflow

Duration: 2 days (2 working days)
Start/end dates: 8/9/23 to 12/9/23 (Weekend included)
