### ISSUE TITLE
2.3.3 Create Class Diagram - Admin

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#49]
Tasks:
- [x] Identify Classes
- [x] Determine Relationships
- [x] Create the Diagram
- [x] Add Attributes
- [x] Add Methods
- [x] Establish Relationships
- [x] Label Relationships
- [x] Document and Annotate
- [x] Organize the Diagram

Goals: Creating a Class Diagram
Completion Criteria: Created Class Diagram
Allocated Time: 8 days
Start & End date : 27/9/23 to 6/10/23

**Comment by wqyeo** [comment]
![M2_Diagrams-Class Diagram - WQ edit(1)](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/6faf7408-7747-4638-8795-0a77111eb072)

First initial state of Class Diagram

**Comment by wqyeo** [comment]
![M2_Diagrams-Class Diagram - NEW](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/d8d74074-64da-4efd-a01c-f612be475f97)

Updated State of Class Diagram

**Comment by wqyeo** [comment]
Class diagram for admin is done successfully and linked up with #81
