### ISSUE TITLE
2.3.7 Refine Sequence Diagram

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#50]
Tasks:
- [x] Ensure the classes are correct
- [x] Ensure the flow is correct
- [x] Implement design patterns / ensure they are correct
- [x] Ensure all descriptions are based off the updated use case diagram

Goals: Ensure that Sequence diagrams attributes and flows follow the lecture slides
Completion Criteria: All sequence diagram attributes are based off of the Class diagram
Allocated Time: 5 days
Start & End date : 16/10/23 to 20/10/23

**Comment by Zhwee** [comment]
![image](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/77541619/db67d2a8-8646-4d1b-a8e5-e9a7d5a80fab)

**Comment by Zhwee** [comment]
![image](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/77541619/e397cf7f-cb78-42f4-8cc1-6be48e61228f)

**Comment by Zhwee** [comment]
Both sequence diagrams for Create New Site and Allocate Jobs to Staff have been refined. The images for classes are according to the lecture slides.
