### ISSUE TITLE
3.1.2 Validate the prototype against user requirements

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#53]

**Comment by ivriahtyx** [comment]
Tasks:

- [x] Verify that all features from the user requirements are present and functional

Goals: To check that the prototype fulfills the specified user requirements and provides the intended features and functionalities.
Completion Criteria: Ensure that the prototype aligns with the documented user requirements without any significant deviations.
Allocated Time: 2 days
Start & End date : 6/11/23 - 7/11/23
