### ISSUE TITLE
3.2.4 Conduct regression testing as needed

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#59]
Tasks: 

tbc....

**Comment by ivriahtyx** [comment]
Tasks: 

- [x] Identify and document any issues or defects found during regression testing
- [x] Re-run regression tests after bug fixes or code modifications to validate

Goals: Ensure that changes in software does not affect existing functionality. 
Completion Criteria:  Check that all identified changes in software are covered by regression tests and is done successfully without critical failures.
Allocated Time: 2 days
Start & End date : 17/11/23 - 20/11/23
