### ISSUE TITLE
2.3.5 Review Sequence Diagram

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#70]
Tasks:
- [x] Examine sequence diagram to ensure that the connection between objects are accurately represented.
- [x] Confirm that sequence follows the correct order and accurately depicts interactions.
- [x] Check for the completeness of the diagram, ensuring all essential interactions and objects are included.
- [x] Verify that roles and responsibilities of object are clearly labeled and consistent.
- [x] Document any issues or recommendations for improvement in the diagram

Goals: To identify and document any concerns or uncertainties present in the sequence diagram.
Completion Criteria: Ensure that all identified issues are clearly highlighted within the sequence diagram, and that the intended message is understood by the refiner.
Allocated Time: 5 days
Start & End date : 09/10/23 - 13/10/23

**Comment by wqyeo** [comment]
Sequence diagram done and determined to have no issues.
