### ISSUE TITLE
2.3.6 Review Class Diagram

### ISSUE THREAD

**Issue by ivriahtyx** [Juicy-Lemonberry/INF2001-P5-2#71]
Tasks:

tbc...

**Comment by 2202348** [comment]
![M2_Diagrams-Class Diagram](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/121930708/21c07244-be9f-4eaf-89c9-335da9d341cb)
Current state of diagram

**Comment by wqyeo** [comment]
Class diagram approved by all with some minor edit and changes.
