### ISSUE TITLE
2.3.4 Create Class Diagram - Staff

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#73]
Tasks:
- [x] Identify Entities:
- [x] Identify Controls:
- [x] Identify Boundaries:
- [x] Define Entity-Control Relationships:
- [x] Define Control-Boundary Relationships:
- [x] Refine Attributes and Methods:
- [x] Specify Relationships
- [x] Annotations and Descriptions:

Goals: To create a class diagram comprising Entity, Control, Boundary, and Interface classes, along with their interconnected relationships.
Completion Criteria: The class diagram must encompass all the classes specified in the user requirements.
Allocated Time: 8 days
Start & End date : 27/09/23 - 06/10/23

**Comment by wqyeo** [comment]
![M2_Diagrams-Class Diagram - WQ edit(1)](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/6faf7408-7747-4638-8795-0a77111eb072)

First initial state of Class Diagram

**Comment by wqyeo** [comment]
![M2_Diagrams-Class Diagram - NEW](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/d8d74074-64da-4efd-a01c-f612be475f97)

Updated State of Class Diagram

**Comment by wqyeo** [comment]
Class diagram for staff is done and linked up successfully with other class diagram components with #81
