### ISSUE TITLE
UML Use Case Diagram

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#8]

**Comment by wqyeo** [comment]
### First Iteration of the Use Case Diagram

![M1_Diagrams](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/4cb6e3bb-0428-444e-a4a8-146c38a739e9)

**Comment by wqyeo** [comment]
Waiting on #15 to gather more information, and then make changes

**Comment by wqyeo** [comment]
![Image](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/16cfb426-e9db-4a58-99d9-1f13fc138252)

Current state of use case diagram after #15 , awaiting for more information and further review of diagram...

**Comment by kazoohaa** [comment]
![Image](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/114292780/07817564-1fb8-445e-abd2-0b80017790c6)

Summary:
Wen Qin created a Use Case diagram for Manager, IT admin and Staff, facilitating a clear visual representation of their interactions with the system in the context of a Workload Management System for the project. The picture above shows the current state of the Use Case diagram after conducting a meeting with the client in #15.

Duration: 2 days
Start/end: 15/9/23 to 18/9/23 (inclusive of weekends)
